### ISSUE TITLE
Changing to any resolution breaks keyboard

### ISSUE THREAD

**Issue by wumbomumbo** [sourcelocation/ResSet16#10]
Any resolution i set my iPhone 11 to breaks my keyboard, on most apps i can't press the numbers and symbols button, i can here on github for example, but i can't on most built in ios apps.

**Comment by jason11501** [comment]
1704x786 fixed keyboard problem

**Comment by wumbomumbo** [comment]
> 1704x786 fixed keyboard problem

that worked thanks 😃
