### ISSUE TITLE
Statusbar bug Please fix it

### ISSUE THREAD

**Issue by iscottt** [sourcelocation/ResSet16#13]
- device: iPhone 13 pro 16.1.2
## When I set the resolution to iPhone 13 pro max , the statusbar will like this.
> Please fix it. thank u so much!!!

![IMG_0821](https://user-images.githubusercontent.com/22902749/223653728-1243912c-422b-4fff-8eb8-d69a4a6e15c4.PNG)

**Comment by sourcelocation** [comment]
try setting an existing resolution of other iphones. if doesn't help, there's no way to fix this
