### ISSUE TITLE
Black screen after setting resolution 

### ISSUE THREAD

**Issue by Logboy2000** [sourcelocation/ResSet16#16]
iPad Air 4
IOS 16.1

I am unable to force reboot using these methods
https://support.apple.com/en-us/HT212017

the only sign of life is taking a screenshot still makes a sound

**Comment by Logboy2000** [comment]
I did fix the issue by letting my iPad die and recharging it. Still a serious issue though

**Comment by sourcelocation** [comment]
Force reboot always works, regardless of OS state. It can even be performed right after the system *starts* to boot up.

**Comment by sourcelocation** [comment]
Sorry for such a long reply :skull: leaving for others to find
