### ISSUE TITLE
Not working on iOS 15.6 RC

### ISSUE THREAD

**Issue by tkiengarrixer** [sourcelocation/ResSet16#2]

**Comment by sourcelocation** [comment]
Device? Try latest release?

**Comment by Yuda897** [comment]
iPhone SE 2016, 15.6 working on 1.1.1

**Comment by tkiengarrixer** [comment]
7 Plus

**Comment by Mjevia** [comment]
This is also my problem right now On my Iphone 6s Plus that it is not working on 15.6 RC when I triy opening the app it just y
says ResSet16 is no longer available so I hope you can fix this
